name: azbox
description: Easy and fast internationalization for your Flutter Apps. Translate your apps using AZBox.
homepage: https://github.com/azbox-io/azbox-localization
issue_tracker: https://github.com/azbox-io/azbox-localization/issues

version: 1.0.12

environment:
  sdk: '>=2.18.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  async: ^2.12.0
  http: ^1.2.2
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0